sudo: required

services:
  - docker

script:
  - docker pull hseeberger/scala-sbt
  - >
    docker run hseeberger/scala-sbt /bin/sh -c
    "
    apt-get -y --force-yes install git;
    git clone https://github.com/daxzel/chin-news /root/chin-news;
    cd /root/chin-news; sbt packageAll
    "