sudo: required

services:
  - docker

script:
  - docker pull hseeberger/scala-sbt
  - >
    docker run --name build hseeberger/scala-sbt /bin/sh -c
    "
    apt-get -y --force-yes install git;
    git clone https://github.com/daxzel/chin-news /root/chin-news;
    cd /root/chin-news; sbt packageAll
    "
  - docker pull daxzel/chin-news
  - docker run --name result daxzel/chin-news
  - docker cp build:/root/chin-news/target/chin-news.zip ./chin-news.zip
  - docker cp ./chin-news.zip result:/root/chin-news.zip
  - >
    docker run --name result /bin/sh -c
    "
    cd /root;
    unzip ./chin-news.zip;
    "
  - docker push daxzel/chin-news
