sudo: required

services:
  - docker

script:
  - docker pull nightscape/docker-sbt
  - >
    docker run nightscape/docker-sbt /bin/sh -c
    "
    apt-get -y --force-yes install git
    git clone https://github.com/daxzel/chin-news /root/chin-news;
    cd /root/chin-news; sbt packageAll
    "