sudo: required

services:
  - docker

script:
  - docker pull hseeberger/scala-sbt
  - >
    docker run --name build hseeberger/scala-sbt /bin/sh -c
    "
    apt-get -y --force-yes install git;
    apt-get -y --force-yes install protobuf-compiler;
    git clone https://github.com/ThesisBestPractices/filtergram /root/filtergram;
    cd /root/filtergram; sbt packageAll
    "

  - docker build -t ThesisBestPractices/filtergram .
  - docker create --name resultTemp ThesisBestPractices/filtergram
  - docker cp build:/root/filtergram/target/filtergram.zip ./filtergram.zip
  - docker cp ./filtergram.zip resultTemp:/root/filtergram.zip
  - docker commit resultTemp ThesisBestPractices/filtergram

  - docker run --name result ThesisBestPractices/filtergram /bin/sh -c "cd /root; rm -r ./app; unzip ./filtergram.zip -d ./app"
  - docker commit result ThesisBestPractices/filtergram
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ThesisBestPractices/filtergram
